### ISSUE TITLE
WebAssembly

### ISSUE THREAD

**Issue by flip111** [418e/Tron#28]
Does the compiler run on WebAssembly (wasm)? Is such feature planned?

**Comment by flip111** [comment]
Thank you for your reply. Close the issue if you like or keep it open in case you like a reminder.

**Comment by 418e** [comment]
Did it as fast as I could
https://wasm.tronlang.org/
https://github.com/tronlang/Tron-Wasm

**Comment by flip111** [comment]
Wow very nice! Would be good to mention on the website and/or readme of main repository that it has a wasm port.
